export interface SeoPage {
  slug: string;
  title: string;
  description: string;
  h1: string;
  subtitle: string;
  tool: string;
  toolLabel: string;
  category: "bg-remover" | "convert" | "merge-pdf" | "pdf-editor";
  color: string;
  keywords: string[];
  features: string[];
  useCases: string[];
}

export const SEO_PAGES: SeoPage[] = [
  // ── Background Remover ──────────────────────────────────────────

  {
    slug: "remove-background-from-photo",
    title: "Remove Background from Photo Free Online",
    description:
      "Remove the background from any photo instantly using AI. Runs in your browser, no uploads required. Free, private, and works offline.",
    h1: "Remove Background from Photo",
    subtitle: "AI-powered background removal that runs 100% in your browser. No sign up, no uploads, no limits.",
    tool: "/bg-remover",
    toolLabel: "Open Background Remover",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["remove background from photo", "photo background remover", "free background removal"],
    features: [
      "AI-powered edge detection for clean cutouts",
      "Replace background with solid colors or custom images",
      "Crop, resize, and adjust brightness/contrast",
      "Download as PNG with transparent background",
    ],
    useCases: [
      "Clean up product photos for your online store",
      "Create professional headshots from casual photos",
      "Make transparent PNGs for presentations and designs",
      "Remove distracting backgrounds from travel photos",
    ],
  },
  {
    slug: "remove-background-from-image",
    title: "Remove Background from Image Free -- AI Background Eraser",
    description:
      "Erase image backgrounds in one click using AI. Works with JPG, PNG, WebP. 100% free and private -- your images never leave your device.",
    h1: "Remove Background from Image",
    subtitle: "Upload any image and get a clean cutout in seconds. No watermarks, no limits, no account needed.",
    tool: "/bg-remover",
    toolLabel: "Remove Background Now",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["remove background from image", "image background eraser", "background removal tool"],
    features: [
      "Works with JPG, PNG, WebP, and more",
      "AI detects subjects automatically",
      "Add new backgrounds or keep transparent",
      "Batch-ready -- process as many images as you need",
    ],
    useCases: [
      "Prepare images for graphic design projects",
      "Create stickers and cutouts from any photo",
      "Remove backgrounds for social media posts",
      "Make transparent logos from existing images",
    ],
  },
  {
    slug: "remove-background-from-selfie",
    title: "Remove Background from Selfie Free Online",
    description:
      "Remove the background from selfies and portraits instantly with AI. Perfect cutouts for profile pictures, resumes, and social media. Free and private.",
    h1: "Remove Background from Selfie",
    subtitle: "Turn any selfie into a professional portrait with a clean or custom background.",
    tool: "/bg-remover",
    toolLabel: "Upload Your Selfie",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["remove selfie background", "selfie background remover", "portrait background removal"],
    features: [
      "AI optimized for human subjects and portraits",
      "Clean hair and edge detection",
      "Replace with solid colors or professional backdrops",
      "Perfect for LinkedIn, resumes, and ID photos",
    ],
    useCases: [
      "Create a professional headshot from a phone selfie",
      "Make passport or ID-style photos at home",
      "Update your LinkedIn profile picture",
      "Create fun profile pictures with custom backgrounds",
    ],
  },
  {
    slug: "remove-background-from-product-photo",
    title: "Remove Background from Product Photo -- Free for E-Commerce",
    description:
      "Get clean white or transparent backgrounds for your product photos. AI-powered, runs locally in your browser. Perfect for Etsy, Amazon, Shopify listings.",
    h1: "Remove Background from Product Photo",
    subtitle: "Clean product images for your online store. White backgrounds, transparent PNGs, no watermarks.",
    tool: "/bg-remover",
    toolLabel: "Clean Product Photos",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["product photo background remover", "ecommerce background removal", "white background product photo"],
    features: [
      "Get marketplace-ready white backgrounds",
      "Export transparent PNGs for any design",
      "Adjust sizing for Amazon, Etsy, or Shopify requirements",
      "Process multiple product photos in one session",
    ],
    useCases: [
      "Prepare product listings for Amazon or Etsy",
      "Create consistent product catalogs",
      "Remove messy backgrounds from handmade item photos",
      "Make professional listings without a photo studio",
    ],
  },
  {
    slug: "remove-background-from-logo",
    title: "Remove Background from Logo -- Make Transparent PNG Free",
    description:
      "Make your logo transparent in seconds. Remove white or colored backgrounds from logos and export as PNG. Free, no sign up required.",
    h1: "Remove Background from Logo",
    subtitle: "Convert any logo to a transparent PNG. Works with JPG, PNG, and scanned logos.",
    tool: "/bg-remover",
    toolLabel: "Make Logo Transparent",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["remove logo background", "transparent logo maker", "logo background remover"],
    features: [
      "Remove white, colored, or complex backgrounds",
      "Export high-quality transparent PNGs",
      "Works with scanned or photographed logos",
      "No quality loss -- keeps original resolution",
    ],
    useCases: [
      "Make a transparent version of your brand logo",
      "Clean up scanned logos for digital use",
      "Prepare logos for overlays on videos or images",
      "Convert JPG logos to transparent PNGs",
    ],
  },
  {
    slug: "remove-background-from-headshot",
    title: "Remove Background from Headshot -- Professional Photos Free",
    description:
      "Create professional headshots by removing backgrounds with AI. Perfect for corporate profiles, resumes, and team pages. Free and private.",
    h1: "Remove Background from Headshot",
    subtitle: "Turn any photo into a professional headshot. Add solid or gradient backgrounds instantly.",
    tool: "/bg-remover",
    toolLabel: "Fix Your Headshot",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["headshot background remover", "professional headshot free", "corporate headshot background"],
    features: [
      "AI-powered subject detection for clean edges",
      "Add professional solid or gradient backgrounds",
      "Crop to standard headshot dimensions",
      "Download in high resolution for print or web",
    ],
    useCases: [
      "Corporate team page photos",
      "Resume and CV headshots",
      "Conference speaker profiles",
      "Professional social media avatars",
    ],
  },
  {
    slug: "transparent-background-maker",
    title: "Transparent Background Maker -- Free Online PNG Tool",
    description:
      "Make any image background transparent instantly. AI removes backgrounds and exports clean PNGs. No uploads to servers -- everything runs in your browser.",
    h1: "Transparent Background Maker",
    subtitle: "Turn any image into a transparent PNG in one click. Free, private, unlimited.",
    tool: "/bg-remover",
    toolLabel: "Make Transparent",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["transparent background maker", "make background transparent", "transparent png maker"],
    features: [
      "One-click background removal with AI",
      "Export as transparent PNG instantly",
      "Works with any image format",
      "No quality degradation or compression",
    ],
    useCases: [
      "Create transparent assets for web design",
      "Make stickers from photos",
      "Prepare images for video editing overlays",
      "Design collages with transparent elements",
    ],
  },
  {
    slug: "ai-background-remover",
    title: "AI Background Remover -- Free, Local, No Upload",
    description:
      "Remove image backgrounds using AI that runs entirely in your browser. No cloud processing, no data collection. The most private background remover online.",
    h1: "AI Background Remover",
    subtitle: "State-of-the-art AI runs directly on your device. Your images never touch a server.",
    tool: "/bg-remover",
    toolLabel: "Try AI Background Remover",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["ai background remover", "local ai background removal", "private background remover"],
    features: [
      "AI model runs on your device via WebGPU/WASM",
      "Zero data sent to any server",
      "Works offline after first load",
      "Handles complex edges like hair and fur",
    ],
    useCases: [
      "Remove backgrounds from confidential documents",
      "Process sensitive images without cloud risk",
      "Work offline on flights or in low-connectivity areas",
      "Bulk process images without usage limits",
    ],
  },
  {
    slug: "remove-white-background",
    title: "Remove White Background from Image Free Online",
    description:
      "Remove white backgrounds from images and make them transparent. Perfect for logos, screenshots, and scanned documents. AI-powered, free, and private.",
    h1: "Remove White Background from Image",
    subtitle: "Convert white backgrounds to transparent in one click. No manual editing needed.",
    tool: "/bg-remover",
    toolLabel: "Remove White Background",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["remove white background", "white background to transparent", "remove white background from image"],
    features: [
      "AI detects and removes white backgrounds automatically",
      "Also handles off-white and light gray backgrounds",
      "Clean edges without manual selection",
      "Export as transparent PNG",
    ],
    useCases: [
      "Make scanned signatures transparent",
      "Clean up screenshots for presentations",
      "Convert white-background logos to transparent",
      "Prepare images for dark-mode websites",
    ],
  },
  {
    slug: "passport-photo-background-remover",
    title: "Passport Photo Background Remover -- Free Online Tool",
    description:
      "Remove and replace passport photo backgrounds with the correct white or light background. AI-powered, runs locally. Free for visa, ID, and passport photos.",
    h1: "Passport Photo Background Remover",
    subtitle: "Get the correct white background for passport and ID photos. Crop to standard sizes.",
    tool: "/bg-remover",
    toolLabel: "Fix Passport Photo",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["passport photo background", "id photo background remover", "visa photo background"],
    features: [
      "Remove any background and replace with white",
      "Crop to passport photo dimensions",
      "Works for visa, ID, and driver's license photos",
      "No uploads -- your photo stays on your device",
    ],
    useCases: [
      "Create passport photos at home",
      "Fix visa application photos",
      "Prepare ID card photos with proper backgrounds",
      "Save money on professional passport photo services",
    ],
  },

  // ── File Converter ──────────────────────────────────────────────

  {
    slug: "jpg-to-pdf",
    title: "Convert JPG to PDF Free Online -- No Upload Required",
    description:
      "Convert JPG images to PDF files instantly in your browser. No file uploads, no servers. Free, private, and works offline.",
    h1: "Convert JPG to PDF",
    subtitle: "Turn your JPG images into PDF documents. Fast, free, and completely private.",
    tool: "/convert",
    toolLabel: "Convert JPG to PDF",
    category: "convert",
    color: "#FFDE59",
    keywords: ["jpg to pdf", "convert jpg to pdf", "jpeg to pdf free"],
    features: [
      "Instant conversion with no file upload",
      "Preserves original image quality",
      "Works with any JPG/JPEG file",
      "Download PDF immediately after conversion",
    ],
    useCases: [
      "Convert scanned documents to PDF",
      "Create PDF portfolios from photos",
      "Submit image-based forms as PDF",
      "Archive photos as PDF documents",
    ],
  },
  {
    slug: "png-to-pdf",
    title: "Convert PNG to PDF Free Online -- Private & Instant",
    description:
      "Convert PNG images to PDF files directly in your browser. High quality, no uploads, no watermarks. Free and unlimited.",
    h1: "Convert PNG to PDF",
    subtitle: "Transform PNG files into PDF documents without losing quality. No sign up, no limits.",
    tool: "/convert",
    toolLabel: "Convert PNG to PDF",
    category: "convert",
    color: "#FFDE59",
    keywords: ["png to pdf", "convert png to pdf", "png to pdf free online"],
    features: [
      "Preserves transparency information",
      "No compression or quality loss",
      "Convert multiple PNGs in sequence",
      "Instant download as PDF",
    ],
    useCases: [
      "Convert screenshots to shareable PDFs",
      "Create documents from design exports",
      "Package PNG illustrations as PDFs",
      "Convert infographics to printable format",
    ],
  },
  {
    slug: "image-to-pdf",
    title: "Convert Image to PDF Free -- JPG, PNG, WebP to PDF",
    description:
      "Convert any image format to PDF for free. Supports JPG, PNG, WebP, GIF, and BMP. All processing happens in your browser -- no uploads, no servers.",
    h1: "Convert Image to PDF",
    subtitle: "Turn any image into a PDF. Supports all major formats. Free, private, instant.",
    tool: "/convert",
    toolLabel: "Convert to PDF",
    category: "convert",
    color: "#FFDE59",
    keywords: ["image to pdf", "convert image to pdf", "photo to pdf"],
    features: [
      "Supports JPG, PNG, WebP, GIF, BMP formats",
      "Maintains original resolution and quality",
      "No file size limits",
      "Works on mobile and desktop browsers",
    ],
    useCases: [
      "Convert camera photos to PDF for email",
      "Create PDF versions of digital art",
      "Package screenshots into documents",
      "Submit image files as PDF attachments",
    ],
  },
  {
    slug: "word-to-pdf",
    title: "Convert Word to PDF Free Online -- DOCX to PDF",
    description:
      "Convert Word documents (.doc, .docx) to PDF entirely in your browser. No upload to servers, no data collection. Free and private.",
    h1: "Convert Word to PDF",
    subtitle: "Transform Word documents into PDF files without uploading them anywhere. 100% local.",
    tool: "/convert",
    toolLabel: "Convert Word to PDF",
    category: "convert",
    color: "#FFDE59",
    keywords: ["word to pdf", "docx to pdf", "convert word to pdf free"],
    features: [
      "Converts .doc and .docx files",
      "Preserves formatting and layout",
      "No Microsoft Office required",
      "Completely local -- no server uploads",
    ],
    useCases: [
      "Convert resumes to PDF before sending",
      "Create PDF versions of reports",
      "Share documents without requiring Word",
      "Archive Word files as PDFs",
    ],
  },
  {
    slug: "webp-to-pdf",
    title: "Convert WebP to PDF Free Online",
    description:
      "Convert WebP images to PDF directly in your browser. No upload, no servers. Free and private with no watermarks.",
    h1: "Convert WebP to PDF",
    subtitle: "Turn WebP files into PDF documents. Fast, free, and completely private.",
    tool: "/convert",
    toolLabel: "Convert WebP to PDF",
    category: "convert",
    color: "#FFDE59",
    keywords: ["webp to pdf", "convert webp to pdf", "webp to pdf free"],
    features: [
      "Full WebP format support",
      "Preserves image quality during conversion",
      "No software installation needed",
      "Instant PDF download",
    ],
    useCases: [
      "Convert web-downloaded images to PDF",
      "Create documents from WebP screenshots",
      "Package WebP assets into printable format",
      "Convert browser-saved images to PDF",
    ],
  },
  {
    slug: "free-file-converter",
    title: "Free File Converter Online -- Convert Images & Docs to PDF",
    description:
      "Convert images and documents to PDF for free. Supports JPG, PNG, WebP, Word, and more. Runs in your browser -- no uploads, no tracking, no limits.",
    h1: "Free File Converter",
    subtitle: "Convert any file to PDF without uploading it to a server. All processing happens on your device.",
    tool: "/convert",
    toolLabel: "Start Converting",
    category: "convert",
    color: "#FFDE59",
    keywords: ["free file converter", "online file converter", "convert to pdf free"],
    features: [
      "Multi-format support: images and documents",
      "Zero server uploads -- total privacy",
      "No account or sign up required",
      "Unlimited conversions with no watermarks",
    ],
    useCases: [
      "Quick document conversion without installing software",
      "Convert files on shared or work computers securely",
      "Process sensitive documents without cloud risk",
      "Convert files on the go from any device",
    ],
  },

  // ── PDF Merger ──────────────────────────────────────────────────

  {
    slug: "merge-pdf-online",
    title: "Merge PDF Online Free -- Combine PDF Files Instantly",
    description:
      "Merge multiple PDF files into one document for free. Drag to reorder pages, preview before download. No uploads -- runs entirely in your browser.",
    h1: "Merge PDF Online",
    subtitle: "Combine multiple PDFs into a single document. Drag to reorder, preview, and download.",
    tool: "/merge-pdf",
    toolLabel: "Merge PDFs Now",
    category: "merge-pdf",
    color: "#4CC9F0",
    keywords: ["merge pdf online", "combine pdf", "merge pdf free"],
    features: [
      "Drag and drop to add and reorder files",
      "Preview pages before merging",
      "Mix PDFs with images in one document",
      "No page limits or file size restrictions",
    ],
    useCases: [
      "Combine invoice or receipt PDFs into one file",
      "Merge chapters into a complete document",
      "Consolidate scanned pages into a single PDF",
      "Create presentation packets from multiple files",
    ],
  },
  {
    slug: "combine-pdf",
    title: "Combine PDF Files Free -- No Upload, No Sign Up",
    description:
      "Combine multiple PDF files into one. All processing happens locally in your browser. Free, private, and unlimited. No account needed.",
    h1: "Combine PDF Files",
    subtitle: "Join multiple PDFs into a single file. Works offline, no data leaves your device.",
    tool: "/merge-pdf",
    toolLabel: "Combine PDFs",
    category: "merge-pdf",
    color: "#4CC9F0",
    keywords: ["combine pdf", "join pdf files", "combine pdf free online"],
    features: [
      "Merge unlimited PDF files at once",
      "Drag to reorder before combining",
      "Preview all pages in the browser",
      "Download combined PDF instantly",
    ],
    useCases: [
      "Combine contract pages into one file",
      "Merge split scan results",
      "Join separate report sections",
      "Consolidate application documents",
    ],
  },
  {
    slug: "merge-images-to-pdf",
    title: "Merge Images to PDF Free -- Combine Photos into One PDF",
    description:
      "Combine multiple images into a single PDF document. Supports JPG, PNG, WebP. Drag to reorder, preview, and download. Free and private.",
    h1: "Merge Images to PDF",
    subtitle: "Turn multiple images into a single PDF document. Perfect for photo albums and portfolios.",
    tool: "/merge-pdf",
    toolLabel: "Merge Images to PDF",
    category: "merge-pdf",
    color: "#4CC9F0",
    keywords: ["merge images to pdf", "combine images into pdf", "multiple images to pdf"],
    features: [
      "Add JPG, PNG, WebP images",
      "Drag to reorder pages",
      "Mix images with existing PDFs",
      "Preview before downloading",
    ],
    useCases: [
      "Create photo albums as PDF",
      "Compile receipts and screenshots",
      "Build image-based portfolios",
      "Package reference images into one file",
    ],
  },
  {
    slug: "pdf-joiner",
    title: "PDF Joiner -- Join PDF Files Free Online",
    description:
      "Join PDF files together without uploading them to any server. Fast, free, and private. Works on any device with a modern browser.",
    h1: "PDF Joiner",
    subtitle: "Join PDF documents into one file. No servers, no uploads, no limits.",
    tool: "/merge-pdf",
    toolLabel: "Join PDFs",
    category: "merge-pdf",
    color: "#4CC9F0",
    keywords: ["pdf joiner", "join pdf files", "pdf joiner online free"],
    features: [
      "Join any number of PDF files",
      "Preserves original formatting and quality",
      "Works offline after first load",
      "No watermarks on output files",
    ],
    useCases: [
      "Join split documents back together",
      "Combine forms with supporting documents",
      "Merge daily reports into weekly summaries",
      "Create single-file submissions from multiple PDFs",
    ],
  },

  // ── PDF Editor ──────────────────────────────────────────────────

  {
    slug: "add-image-to-pdf",
    title: "Add Image to PDF Free Online -- Drag & Drop Editor",
    description:
      "Add images to any PDF page. Drag to position, resize visually, and download. Free, private, no upload to servers.",
    h1: "Add Image to PDF",
    subtitle: "Place images anywhere on your PDF pages. Drag, resize, and download. Completely free.",
    tool: "/pdf-editor",
    toolLabel: "Add Images to PDF",
    category: "pdf-editor",
    color: "#FF914D",
    keywords: ["add image to pdf", "insert image in pdf", "overlay image on pdf"],
    features: [
      "Visual drag-and-drop image placement",
      "Resize images on any page",
      "Add multiple images across pages",
      "Preserves original PDF content",
    ],
    useCases: [
      "Add a signature image to contracts",
      "Insert a logo on every page of a report",
      "Add stamps or watermarks to documents",
      "Place photos into PDF templates",
    ],
  },
  {
    slug: "pdf-image-editor",
    title: "PDF Image Editor Free -- Insert Photos into PDF Online",
    description:
      "Edit PDFs by inserting images onto any page. Visual editor with drag-and-drop positioning. Free, no uploads, runs in your browser.",
    h1: "PDF Image Editor",
    subtitle: "A visual editor for placing images onto PDF pages. No software to install.",
    tool: "/pdf-editor",
    toolLabel: "Open PDF Editor",
    category: "pdf-editor",
    color: "#FF914D",
    keywords: ["pdf image editor", "edit pdf images", "insert photo in pdf"],
    features: [
      "WYSIWYG editing interface",
      "Drag and drop images onto pages",
      "Resize and reposition freely",
      "Download edited PDF instantly",
    ],
    useCases: [
      "Annotate PDFs with reference images",
      "Add product photos to spec sheets",
      "Insert diagrams into reports",
      "Customize PDF templates with images",
    ],
  },
  {
    slug: "add-signature-to-pdf",
    title: "Add Signature to PDF Free Online -- No Upload Required",
    description:
      "Add your signature image to any PDF document. Drag to position, resize to fit. Free, private -- your document never leaves your browser.",
    h1: "Add Signature to PDF",
    subtitle: "Place your signature anywhere on a PDF. Private, free, no account needed.",
    tool: "/pdf-editor",
    toolLabel: "Add Signature",
    category: "pdf-editor",
    color: "#FF914D",
    keywords: ["add signature to pdf", "sign pdf free", "insert signature pdf"],
    features: [
      "Upload your signature as an image",
      "Position it precisely on any page",
      "Resize to match signature lines",
      "Document never uploaded to any server",
    ],
    useCases: [
      "Sign contracts and agreements digitally",
      "Add signatures to forms without printing",
      "Sign rental or lease agreements remotely",
      "Complete signed document requests quickly",
    ],
  },
  {
    slug: "add-logo-to-pdf",
    title: "Add Logo to PDF Free -- Brand Your Documents Online",
    description:
      "Add your company logo to PDF documents. Place on any page, resize, and position visually. Free tool that runs in your browser.",
    h1: "Add Logo to PDF",
    subtitle: "Brand your PDF documents by adding your logo to any page. Free and private.",
    tool: "/pdf-editor",
    toolLabel: "Add Your Logo",
    category: "pdf-editor",
    color: "#FF914D",
    keywords: ["add logo to pdf", "insert logo in pdf", "brand pdf with logo"],
    features: [
      "Place logo on any page of the PDF",
      "Resize and position with drag-and-drop",
      "Works with PNG, JPG, and WebP logos",
      "Add to multiple pages at once",
    ],
    useCases: [
      "Brand invoices with your company logo",
      "Add logos to proposals and presentations",
      "Customize PDF templates with branding",
      "Watermark documents with your logo",
    ],
  },
  {
    slug: "free-pdf-editor",
    title: "Free PDF Editor Online -- Edit PDFs in Your Browser",
    description:
      "Edit PDF files for free. Add images, signatures, and logos to any page. Visual editor that runs locally -- no uploads, no servers, no sign up.",
    h1: "Free PDF Editor",
    subtitle: "Edit PDFs without installing software. Add images, resize, reposition, and download.",
    tool: "/pdf-editor",
    toolLabel: "Edit PDF Free",
    category: "pdf-editor",
    color: "#FF914D",
    keywords: ["free pdf editor", "edit pdf online", "pdf editor no sign up"],
    features: [
      "Visual drag-and-drop editing",
      "Add images and overlays to any page",
      "Resize and position elements freely",
      "No software installation or account required",
    ],
    useCases: [
      "Quick edits without Adobe Acrobat",
      "Add missing images to documents",
      "Prepare documents on shared computers",
      "Edit PDFs on any device with a browser",
    ],
  },

  // ── General / Multipurpose ──────────────────────────────────────

  {
    slug: "free-online-photo-editor",
    title: "Free Online Photo Editor -- Edit Photos in Your Browser",
    description:
      "Edit photos for free online. Remove backgrounds, adjust brightness and contrast, crop, add text, and more. No uploads, 100% private.",
    h1: "Free Online Photo Editor",
    subtitle: "Edit your photos directly in the browser. Remove backgrounds, crop, filter, and export.",
    tool: "/bg-remover",
    toolLabel: "Edit Photos Free",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["free photo editor", "online photo editor", "edit photos free"],
    features: [
      "AI background removal",
      "Brightness, contrast, and saturation controls",
      "Crop to custom or preset aspect ratios",
      "Add text overlays with custom fonts",
    ],
    useCases: [
      "Quick photo edits without installing Photoshop",
      "Fix photos on the go from your phone",
      "Prepare images for social media",
      "Edit photos on work computers without admin rights",
    ],
  },
  {
    slug: "free-pdf-tools",
    title: "Free PDF Tools Online -- Merge, Edit, Convert PDFs",
    description:
      "All-in-one free PDF toolkit. Merge PDFs, add images, convert files to PDF. Everything runs in your browser. No uploads, no limits, no sign up.",
    h1: "Free PDF Tools",
    subtitle: "Merge, edit, and convert PDFs without uploading your files. 100% private and free.",
    tool: "/merge-pdf",
    toolLabel: "Open PDF Tools",
    category: "merge-pdf",
    color: "#4CC9F0",
    keywords: ["free pdf tools", "pdf tools online", "pdf toolkit free"],
    features: [
      "Merge multiple PDFs into one",
      "Add images and signatures to PDFs",
      "Convert images and Word docs to PDF",
      "All processing happens locally",
    ],
    useCases: [
      "Handle all PDF tasks without paid software",
      "Process sensitive documents privately",
      "Work with PDFs on any device",
      "Quick PDF fixes without installing anything",
    ],
  },
  {
    slug: "private-file-tools",
    title: "Private File Tools -- No Upload, No Tracking, Free",
    description:
      "File editing tools that never upload your data. Background removal, PDF editing, file conversion -- all running 100% in your browser. Free and offline-capable.",
    h1: "Private File Tools",
    subtitle: "Tools that respect your privacy. No uploads, no tracking, no accounts. Your files stay on your device.",
    tool: "/",
    toolLabel: "Browse All Tools",
    category: "bg-remover",
    color: "#A7F205",
    keywords: ["private file tools", "no upload file editor", "offline file tools"],
    features: [
      "Zero data sent to servers -- ever",
      "Works offline after first load",
      "No accounts or tracking",
      "Open source processing in your browser",
    ],
    useCases: [
      "Handle confidential documents safely",
      "Edit files on restricted networks",
      "Process files without trusting third-party servers",
      "Work with sensitive images and documents",
    ],
  },
  {
    slug: "offline-image-editor",
    title: "Offline Image Editor -- Edit Photos Without Internet",
    description:
      "An image editor that works offline. Remove backgrounds, crop, adjust colors, and add text -- all without an internet connection after first load.",
    h1: "Offline Image Editor",
    subtitle: "Edit images anytime, anywhere. No internet required after the first visit.",
    tool: "/bg-remover",
    toolLabel: "Open Image Editor",
    category: "bg-remover",
    color: "#FF6B6B",
    keywords: ["offline image editor", "edit images offline", "no internet photo editor"],
    features: [
      "Full functionality without internet",
      "AI background removal works offline",
      "Crop, filter, and text editing offline",
      "No data ever sent to external servers",
    ],
    useCases: [
      "Edit photos during flights",
      "Work in areas with poor connectivity",
      "Process images on air-gapped computers",
      "Reliable editing without depending on cloud services",
    ],
  },
  {
    slug: "no-upload-file-editor",
    title: "No Upload File Editor -- Edit Files Without Uploading",
    description:
      "Edit images and PDFs without uploading them anywhere. All processing happens in your browser using local AI. Free, private, and secure.",
    h1: "No Upload File Editor",
    subtitle: "Your files never leave your device. Edit images, PDFs, and documents 100% locally.",
    tool: "/",
    toolLabel: "Browse Tools",
    category: "bg-remover",
    color: "#A7F205",
    keywords: ["no upload editor", "local file editor", "browser file editor"],
    features: [
      "All processing runs client-side",
      "No server communication during editing",
      "Works with images, PDFs, and documents",
      "Free with no usage limits",
    ],
    useCases: [
      "Edit sensitive corporate documents",
      "Process medical or legal images privately",
      "Work on files covered by NDA or compliance rules",
      "Use on shared computers without privacy concerns",
    ],
  },
];
